### ISSUE TITLE
Log car tours

### ISSUE THREAD

**Issue by dorthrithil** [dorthrithil/car-sharing-app-server#3]
#### A car tour has the following properties:

- start km
- end km
- start datetime
- end datetime
- parking position
- is payed (true after cash balancing)
- owner
- community
- comment
- was force finished (if other user finished tour because owner forgot to)
- force finished by (user id of force finishing user)

#### Start a tour:

- Sets Start km (automatically)
- Sets start datetime
- Sets is payed to false
- Sets owner
- Sets community
- Can only be done by accepted community member
- Must check for unfinished previous car tours
- `POST /communities/{community-id}/tours`

#### Finish a tour

- Sets End km
- Sets end datetime
- Sets parking position (optional)
- Sets comment (optional)
- Can only be done by tour owner
- `PUT /communities/{community-id}/tours/{id}/finish`

#### Edit a tour

- Can change comment
- Can change End km if no tour was logged afterwards
- Can change parking position
- Can only be done by tour owner
- `PUT /communities/{community-id}/tours/{id}`

#### Delete a tour

- Deletes a tour
- Can only be done by tour owner
- Can only be done if no tour was logged afterwards
- `DELETE /communities/{community-id}/tours/{id}`

#### View tours of community

- Shows all finished tours of the community
- Can only be done by community member
- `GET /communities/{community-id}/tours`

#### View tour detail

- Shows the tour details (tour + comment and parking spot)
- Can only be done by community member
- `GET /communities/{community-id}/tours/{id}`

#### View user tours

- Shows all finished tours of a user
- Can only be done by user himself
- `GET /account/tours`

#### Force finish existing tour

- Finishes a tour that another user forgot to finish
- Sets End km
- Sets end datetime
- Sets comment 
- Sets force finished fields (bool and user id)
- Can only be done by community member
- Cannot be done by tour owner
- `PUT /communities/{community-id}/tours/{id}/force-finish`

#### Show running tours for community

- Shows all running tours of a community
- Can only be done by community member
- `GET /communities/{community-id}/tours/running`

#### Show running tours for user

- Shows all running tours of a user
- Can only be done by user himself
- `GET /account/tours/running`

### TODOs

- [x] Create model
- [x] `POST /communities/{community-id}/tours`
- [x] `PUT /communities/{community-id}/tours/{id}/finish`
- [x] `PUT /communities/{community-id}/tours/{id}`
- [x] `DELETE /communities/{community-id}/tours/{id}`
- [x] `GET /communities/{community-id}/tours`
- [x] `GET /communities/{community-id}/tours/running`
- [x] `GET /communities/{community-id}/tours/{id}`
- [x] `GET /account/tours`
- [x] `GET /account/tours/running`
- [x] `PUT /communities/{community-id}/tours/{id}/force-finish`
