### ISSUE TITLE
Payoff

### ISSUE THREAD

**Issue by dorthrithil** [dorthrithil/car-sharing-app-server#5]
### Debt model

- Debtee
- Recipient
- Payoff id
- isSettled
- Amount

### Payoff model

- Debts List
- isSettled
- Community
- List of refuels
- List of tours
- List of involved users

### Create payoff

- Collects all open tours and refuels
- Creates the minimal number of debt objects to settle all costs
- Can only be done by community member 
- Can only be done when no open tour exists in community
- `POST /communities/{id}/payoffs`

### Get payoff detail

- Get all info for a payoff
- Can only be seen by community members
- `GET /communities/{community-id}/payoffs/{id}`

### Get all community payoffs 

- Get all payoffs of a community
- Can only be seen by community members
- `GET /communities/{community-id}/payoffs`

### Get all unsettled community debts

- Get all debts that are unsettled in a community
- Can only be seen by community members
- `GET /communities/{community-id}/debts/open`

### Get all unsettled user debts

- Get all debts that are unsettled for the calling user (debtee or recipient)
- `GET /account/debts/open`

### Settle debt

- Sets a debt to settles status
- If this is the last unsettled debt of a payoff, the payoff is settled too
- Can be done by debtee or recipient
- `PUT /communities/{community-id}/debts/{id}`

### TODOs

- [x] Payoff model
- [x] Debt model
- [x] `POST /communities/{id}/payoffs`
- [x] `GET /communities/{community-id}/payoffs/{id}`
- [x] `GET /communities/{community-id}/payoffs`
- [x] `GET /communities/{community-id}/debts/open`
- [x] `GET /account/debts/open`
- [x] `PUT /communities/{community-id}/debts/{id}`
